// <auto-generated />
using System;
using BolindersBil.Web.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BolindersBil.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BolindersBil.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("BolindersBil.Models.Office", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int?>("AdminsId");

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<int>("PhoneNumber");

                    b.Property<int>("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("AdminsId");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("BolindersBil.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("Body");

                    b.Property<string>("Brand");

                    b.Property<string>("Color");

                    b.Property<string>("Fuel");

                    b.Property<string>("Gearbox");

                    b.Property<int>("Horsepower");

                    b.Property<int>("Kilometer");

                    b.Property<bool>("Leasable");

                    b.Property<string>("Model");

                    b.Property<string>("OfficesId");

                    b.Property<string>("Picture");

                    b.Property<double>("Price");

                    b.Property<string>("RegNr");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<bool>("Used");

                    b.Property<string>("VehicleAttribute");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("OfficesId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("BolindersBil.Models.Office", b =>
                {
                    b.HasOne("BolindersBil.Models.Admin", "Admins")
                        .WithMany()
                        .HasForeignKey("AdminsId");
                });

            modelBuilder.Entity("BolindersBil.Models.Vehicle", b =>
                {
                    b.HasOne("BolindersBil.Models.Office", "Offices")
                        .WithMany("Vehicles")
                        .HasForeignKey("OfficesId");
                });
#pragma warning restore 612, 618
        }
    }
}
